apiVersion: devops.alauda.io/v1alpha1
kind: PipelineTemplate
metadata:
  annotations:
    displayName.en: 'Template of PipelineConfig '
    displayName.zh-CN: 'Template of PipelineConfig '
    style.icon: "0.1"
    templateMoldHash: 99cbfc649
    version: "0.1"
  creationTimestamp: null
  finalizers:
  - pipelineconfig-referenced
  labels:
    category: PipelineConfigTemplate
    latest: "true"
    source: customer
    templateName: -template-99cbfc649
  name: -template-99cbfc649
  namespace: maigoo
spec:
  agent:
    label: ""
    labelMatcher: ""
    raw: ""
  arguments:
  - description: {}
    displayName:
      en: Git Clone
      zh-CN: Git Clone
    items:
    - binding:
      - clone.args.PlatformCodeRepository
      default: ""
      display:
        description:
          en: Select a code repository for the project.
          zh-CN: 请选择或输入要检出的代码仓库
        name:
          en: RepositoryPath
          zh-CN: 代码仓库
        type: integrations.katanomi.dev/coderepository
      name: clone__PlatformCodeRepository
      required: true
      schema:
        type: integrations.katanomi.dev/coderepository
      value: ""
    - binding:
      - clone.args.RelativeDirectory
      default: .
      display:
        description:
          en: Specify a local directory (relative to the workspace root) where the
            Git repository will be checked out. If left empty, the workspace root
            itself will be used
          zh-CN: 指定签出 Git 仓库的本地目录(相对于 workspace 根目录)。若为空，将使用 workspace 根目录
        name:
          en: RelativeDirectory
          zh-CN: 相对目录
        type: string
      name: clone__RelativeDirectory
      required: false
      schema:
        type: string
      value: ""
    - binding:
      - clone.args.Timeout
      default: "10"
      display:
        advanced: true
        description:
          en: If the execution time of the current code pull exceeds the timeout time,
            the task will be aborted and the pipeline will become a failed state
          zh-CN: 当前代码拉取的执行时间若超过超时时间，则会中止任务，流水线变为失败状态
        name:
          en: Timeout (min)
          zh-CN: 超时时间（分钟）
        type: string
      name: clone__Timeout
      required: false
      schema:
        type: string
      validation:
        maxLength: 36
        pattern: ^[1-9]\d*$
      value: ""
    - binding:
      - clone.args.ShallowClone
      default: "false"
      display:
        description:
          en: Create a shallow clone with a history truncated to the 1 of commits
          zh-CN: 开启后仅拉取代码仓库最新版本
        name:
          en: shallow clone
          zh-CN: 浅克隆
        type: boolean
      name: clone__ShallowClone
      required: true
      schema:
        type: boolean
      value: ""
    - binding:
      - clone.args.GitConfig
      default: ""
      display:
        advanced: true
        description:
          en: 'Support for entering git configuration parameters, e.g.: $ git config
            --global user.name ''username'''
          zh-CN: '支持输入git的配置参数, 例如: $ git config --global user.name ''用户名'''
        name:
          en: Custom git config
          zh-CN: 自定义git参数设置
        type: code
      name: clone__GitConfig
      required: false
      schema:
        type: string
      value: ""
  - description: {}
    displayName:
      en: Golang Build
      zh-CN: Golang构建
    items:
    - binding:
      - golang.args.buildCommand
      default: go build
      display:
        description:
          en: 'build command. Defaults to: go build'
          zh-CN: 自定义更详细的构建命令。默认为：go build
        name:
          en: Build Command
          zh-CN: 构建命令
        type: code
      name: golang__buildCommand
      required: false
      schema:
        type: string
      value: ""
  - description: {}
    displayName:
      en: CodeScan
      zh-CN: 代码扫描
    items:
    - binding:
      - sonar.args.CodeQualityBinding
      default: ""
      display:
        args:
          integrationClass: sonarqube
        description:
          en: Select a SonarQube binding
          zh-CN: 选择要使用的SonarQube
        name:
          en: SonarQube
          zh-CN: SonarQube
        type: integrations.katanomi.dev/integration
      name: sonar__CodeQualityBinding
      required: true
      schema:
        type: integrations.katanomi.dev/integration
      value: ""
    - binding:
      - sonar.args.EnableBranchAnalysis
      default: "false"
      display:
        description:
          en: Enable to distinguish scanned code branches
          zh-CN: 开启后可区分扫描的代码分支
        name:
          en: Enable branch analysis
          zh-CN: 区分代码分支
        type: boolean
      name: sonar__EnableBranchAnalysis
      required: false
      schema:
        type: boolean
      value: ""
    - binding:
      - sonar.args.AnalysisParameters
      default: ""
      display:
        description:
          en: Set analysis parameters for Sonar Scanner. When 'sonar-project.properties'
            existed in project, this argument will reset parameters which name in
            argument. see <a href="/console-devops/docs/devops-u-cd/pipeline/createpipeline/createpattern/pipelinetask/#codescan"
            target="_blank">help</a> for more details<br><br>Parameter example:<br>sonar.resource=.<br>sonar.sourceEncoding=UTF-8
          zh-CN: '为 Sonar Scanner 设置分析参数。当目录中存在 sonar-project.properties 文件时，这个参数将会覆盖文件中的相同参数名的配置。详细参数见文档:
            <a href="/console-devops/docs/devops-u-cd/pipeline/createpipeline/createpattern/pipelinetask/#codescan"
            target="_blank">帮助文档</a><br><br>参数示例:<br>sonar.resource=.<br>sonar.sourceEncoding=UTF-8'
        name:
          en: Analysis Parameters
          zh-CN: 代码扫描参数
        type: stringMultiline
      name: sonar__AnalysisParameters
      required: false
      schema:
        type: string
      value: ""
    - binding:
      - sonar.args.FailedIfNotPassQualityGate
      default: "false"
      display:
        description:
          en: Fails pipeline execution when quality gate fails
          zh-CN: 开启后，代码扫描结果为失败时，流水线执行状态变为失败，终止流水线
        name:
          en: Fail pipeline when quality gate fails
          zh-CN: 质量阈未通过终止流水线
        type: boolean
      name: sonar__FailedIfNotPassQualityGate
      required: false
      schema:
        type: boolean
      value: ""
    - binding:
      - sonar.args.timeout
      default: "30"
      display:
        description:
          en: The longest waiting time for code scanning, beyond which the pipeline
            is aborted.
          zh-CN: 代码扫描运行的最长等待时间，超出该时间，流水线执行终止。
        name:
          en: Timeout(m)
          zh-CN: 超时时间(分钟)
        type: string
      name: sonar__timeout
      required: false
      schema:
        type: string
      value: ""
  - description: {}
    displayName:
      en: Image Build
      zh-CN: 镜像构建
    items:
    - binding:
      - build-docker.args.imageRepository
      default: ""
      display:
        args:
          mode: push
        description:
          zh-CN: 选择或者输入镜像仓库
        name:
          en: Repository
          zh-CN: 镜像仓库
        type: integrations.katanomi.dev/imagerepository
      name: build-docker__imageRepository
      required: true
      schema:
        type: integrations.katanomi.dev/imagerepository
      value: ""
    - binding:
      - build-docker.args.dockerfile
      default: Dockerfile
      display:
        description:
          zh-CN: Dockerfile 在代码仓库中的绝对路径
        name:
          en: Dockerfile
          zh-CN: Dockerfile
        type: string
      name: build-docker__dockerfile
      required: true
      schema:
        type: string
      value: ""
    - binding:
      - build-docker.args.context
      default: .
      display:
        description:
          en: The build process can refer to any of the files in the context. For
            example, your build can use a COPY instruction to reference a file in
            the context
          zh-CN: 构建过程可以引用上下文中的任何文件。例如，构建中可以使用 COPY 命令在上下文中引用文件
        name:
          en: Build Context
          zh-CN: 构建上下文
        type: string
      name: build-docker__context
      required: false
      schema:
        type: string
      value: ""
    - binding:
      - build-docker.args.buildArguments
      default: ""
      display:
        description:
          zh-CN: 自定义build Options，如 --add-host，多个 Options 用空格隔开；可参考 https://docs.docker.com/engine/reference/commandline/build/
        name:
          en: Build Arguments
          zh-CN: 构建参数
        type: string
      name: build-docker__buildArguments
      required: false
      schema:
        type: string
      value: ""
    - binding:
      - build-docker.args.retry
      default: "3"
      display:
        description:
          zh-CN: 生成镜像时的失败重试次数
        name:
          en: Retry Times
          zh-CN: 重试次数
        type: string
      name: build-docker__retry
      required: false
      schema:
        type: string
      value: ""
    - binding:
      - build-docker.args.format
      default: docker
      display:
        advanced: true
        description:
          en: specify the image format
          zh-CN: 指定镜像构建格式
        enumAlias:
        - Docker格式
        - OCI格式
        name:
          en: Image Format
          zh-CN: 镜像构建格式
        type: radio
      name: build-docker__format
      required: true
      schema:
        enum:
        - docker
        - oci
        type: string
      value: ""
  - description: {}
    displayName:
      en: Deploy Application
      zh-CN: 部署应用
    items:
    - binding:
      - deployService.args.createApp
      default: "false"
      display:
        description:
          en: Close to update existing applications. Such as open, please place the
            YAML, JSON resource files in the selected code warehouse, applications
            will be created under the selected cluster and namespace, created for
            the first time to perform assembly line for creating applications, subsequent
            to update application
          zh-CN: 关闭为更新已有应用；如开启，请将YAML、JSON资源文件放置在所选代码仓库中，应用将在下面选择的集群和命名空间下创建，创建后首次执行流水线为创建应用、后续为更新应用
        name:
          en: create application
          zh-CN: 创建应用
        type: boolean
      name: deployService__createApp
      required: false
      schema:
        type: boolean
      value: ""
    - binding:
      - deployService.args.clusterName
      default: ""
      display:
        description:
          en: cluster
          zh-CN: 应用所在的集群
        name:
          en: cluster
          zh-CN: 集群
        type: alauda.io/clustername
      name: deployService__clusterName
      required: true
      schema:
        type: string
      value: ""
    - binding:
      - deployService.args.namespace
      default: ""
      display:
        description:
          en: namespace
          zh-CN: 应用所在的命名空间
        name:
          en: namespace
          zh-CN: 命名空间
        related: deployService__clusterName
        type: alauda.io/namespace
      name: deployService__namespace
      required: true
      schema:
        type: string
      value: ""
    - binding:
      - deployService.args.serviceName
      default: ""
      display:
        args:
          clusterName: deployService__clusterName
        description:
          en: application
          zh-CN: |-
            *组件类型包括“部署”、“守护进程集”、“有状态副本集” 三类
            *已关联应用：通过“应用”功能创建的“计算组件”，显示格式为“应用名称/组件类型/组件名称”
            *未关联应用：未通过“应用”功能创建的“计算组件”，显示格式为“组件类型/组件名称”
        name:
          en: application
          zh-CN: 应用
        related: deployService__namespace
        type: alauda.io/servicenamemix
      name: deployService__serviceName
      relation:
      - action: hidden
        when:
          name: deployService__createApp
          value: true
      required: true
      schema:
        type: string
      value: ""
    - binding:
      - deployService.args.containerName
      default: ""
      display:
        args:
          clusterName: deployService__clusterName
          namespace: deployService__namespace
        description:
          en: The name of the container instance that needs to be updated
          zh-CN: 需要更新的容器实例名称
        name:
          en: container
          zh-CN: 容器
        related: deployService__serviceName
        type: alauda.io/containername
      name: deployService__containerName
      relation:
      - action: hidden
        when:
          name: deployService__createApp
          value: true
      required: true
      schema:
        type: string
      value: ""
    - binding:
      - deployService.args.deployConfigFolder
      default: ""
      display:
        description:
          en: 1.The path to the YAML and JSON files in the selected code repository,
            such as 'a/b/c', as much as possible to avoid errors, please ensure that
            the selected folder contains only the Kubernetes YAML, JSON resource files;
            2.Creating a reference that only supports single-app creation, such as
            a definition of multiple apps in YAML, JSON files, will fail to be created
          zh-CN: 1.所选代码仓库中YAML、JSON文件的路径，如'a/b/c'，为避免出错，请尽可能保证所选文件夹下仅包含YAML、JSON的Kubernetes资源文件;
            2.创建应用仅支持单应用创建，如YAML、JSON文件中存在多个应用的定义，则会创建失败
        name:
          en: Deploy Configuration Directory
          zh-CN: 部署配置目录
        type: string
      name: deployService__deployConfigFolder
      relation:
      - action: show
        when:
          name: deployService__createApp
          value: true
      required: true
      schema:
        type: string
      value: ""
    - binding:
      - deployService.args.container
      default: ""
      display:
        description:
          en: The name of the container in which the image is run
          zh-CN: 构建出的镜像运行的容器名
        name:
          en: container
          zh-CN: 容器
        type: string
      name: deployService__container
      relation:
      - action: show
        when:
          name: deployService__createApp
          value: true
      required: true
      schema:
        type: string
      value: ""
    - binding:
      - deployService.args.imageRepositoryDeploy
      default: ""
      display:
        args:
          mode: pull
        description:
          en: image repo
          zh-CN: 选择或者输入镜像仓库
        name:
          en: Repository
          zh-CN: 镜像仓库
        type: integrations.katanomi.dev/imagerepository
      name: deployService__imageRepositoryDeploy
      required: true
      schema:
        type: integrations.katanomi.dev/imagerepository
      value: ""
    - binding:
      - deployService.args.rollback
      default: ""
      display:
        description:
          en: After updating application, such as application cannot run normally,
            roll back to the previous of the updated version
          zh-CN: 更新应用后，如应用不能正常运行，则回滚到更新前的版本
        name:
          en: rollbackOnFailure
          zh-CN: 失败后回滚
        type: boolean
      name: deployService__rollback
      relation:
      - action: hidden
        when:
          name: deployService__createApp
          value: true
      required: false
      schema:
        type: boolean
      value: ""
    - binding:
      - deployService.args.command
      default: ""
      display:
        advanced: true
        description:
          en: command
          zh-CN: 即 command，相当于 Dockerfile 中的 ENTRYPOINT 命令。如果没有指定启动命令，将使用容器镜像中的 ENTRYPOINT
        name:
          en: command
          zh-CN: 启动命令
        type: string
      name: deployService__command
      relation:
      - action: hidden
        when:
          name: deployService__createApp
          value: true
      required: false
      schema:
        type: string
      value: ""
    - binding:
      - deployService.args.args
      default: ""
      display:
        advanced: true
        description:
          en: args
          zh-CN: 即 args，相当于 Dockerfile 中的 CMD，负责提供启动命令的命令参数。如果没有指定参数，将使用容器镜像中的 CMD
        name:
          en: args
          zh-CN: 参数
        type: string
      name: deployService__args
      relation:
      - action: hidden
        when:
          name: deployService__createApp
          value: true
      required: false
      schema:
        type: string
      value: ""
    - binding:
      - deployService.args.timeout
      default: ""
      display:
        description:
          en: If the execution time of the current task exceeds the timeout time,
            the task will be aborted and the pipeline will become a failed state
          zh-CN: 当前任务的执行时间若超过超时时间，则会中止任务，流水线变为失败状态
        name:
          en: Timeout (s)
          zh-CN: 超时时间（秒）
        type: string
      name: deployService__timeout
      required: true
      schema:
        type: string
      value: ""
  engine: graph
  options:
    raw: ""
    timeout: 0
  stages:
  - display: {}
    name: clone
    tasks:
    - display: {}
      kind: ClusterPipelineTaskTemplate
      name: clone
      showParameters: true
      type: ""
  - display: {}
    name: golang-build
    tasks:
    - display: {}
      kind: ClusterPipelineTaskTemplate
      name: golang
      showParameters: null
      type: ""
  - display: {}
    name: code-scan
    tasks:
    - display: {}
      kind: ClusterPipelineTaskTemplate
      name: sonar
      showParameters: null
      type: ""
  - display: {}
    name: image-build
    tasks:
    - display: {}
      kind: ClusterPipelineTaskTemplate
      name: build-docker
      showParameters: null
      type: ""
  - display: {}
    name: deployservice
    tasks:
    - display: {}
      kind: ClusterPipelineTaskTemplate
      name: deployService
      showParameters: false
      type: ""
  triggers:
    raw: ""
  withSCM: false
status:
  phase: ""
