apiVersion: devops.alauda.io/v1alpha1
kind: PipelineTemplate
metadata:
  annotations:
    displayName.en: 'Template of PipelineConfig '
    displayName.zh-CN: 'Template of PipelineConfig '
    style.icon: "0.1"
    templateMoldHash: 5c89cd6744
    version: "0.1"
  creationTimestamp: null
  finalizers:
  - pipelineconfig-referenced
  labels:
    category: PipelineConfigTemplate
    latest: "true"
    source: customer
    templateName: -template-5c89cd6744
  name: -template-5c89cd6744
  namespace: maigoo
spec:
  agent:
    label: ""
    labelMatcher: ""
    raw: ""
  arguments:
  - description: {}
    displayName:
      en: Python Build
      zh-CN: Python构建
    items:
    - binding:
      - python.args.buildCommand
      default: pip install -r requirements.txt
      display:
        description:
          en: Build command. Defaults to pip install -r requirements.txt
          zh-CN: 自定义更详细的构建命令。默认为：pip install -r requirements.txt
        name:
          en: Build Command
          zh-CN: 构建命令
        type: code
      name: python__buildCommand
      required: false
      schema:
        type: string
      value: ""
  engine: graph
  options:
    raw: ""
    timeout: 0
  stages:
  - display: {}
    name: ""
    tasks:
    - display: {}
      kind: ClusterPipelineTaskTemplate
      name: python
      showParameters: null
      type: ""
  triggers:
    raw: ""
  withSCM: false
status:
  phase: ""
